### ISSUE TITLE
vim编辑的时候行号出错

### ISSUE THREAD

**Issue by Akemi-Homura** [DanteLee/ndslvim#1]
vim编辑的时候行号显示是错误的
![image](https://user-images.githubusercontent.com/16780053/34724720-dc6aa3a2-f589-11e7-94fe-61f56310c280.png)
如图所示，只有行号8是对的，其他都是错误的

**Comment by c0x0o** [comment]
其实这不是一个错误，你会发现其他的行号是相对于该行的偏移量，方便用5dd这种快速删除或者copy指令。在普通模式下会这样显示行号，但是在编辑模式下，会正常显示每一行的行号。

**Comment by Akemi-Homura** [comment]
原来是这样，我还是比较习惯用行号来跳转。谢了！:D
