### ISSUE TITLE
安装部分操作

### ISSUE THREAD

**Issue by Arabira1** [DanteLee/ndslvim#2]
安装部分没有提示用户去掉或者屏蔽原生.vim目录和.viminfo文件

**Comment by Arabira1** [comment]
提示用户遇到 YouCompleteMe unavailable: No module named 'future' 问题时安装pip3，执行以下指令：
sudo pip3 install future

提示用户遇到 YouCompleteMe unavailable no module named frozendict或者 YouCompleteMe unavailable no module named future时：
进入到YouCompleteMe目录，在terminal窗口敲入git submodule update --init --recursive

提示用户遇到 The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). YCM core library not detected; you need to compile YCM before using it. Follow the instructions in the documentation 时进入工程下的youCompleteMe目录执行以下指令：
python install.py
如果提示安装cmake，提示用户执行以下指令：
sudo apt install cmake（ubuntu16.04 or higher）
sudo apt-get install cmake(ubuntu14.04)

**Comment by c0x0o** [comment]
已经在README中作出相应的调整
